version: '3'

services:
  redis:
    image: redis
    networks:
      - deployml_network

  modelserver:
    image: ankit/modelserver
    build: ./modelserver
    depends_on:
      - redis
    networks:
      - deployml_network
    env_file:
      - app.env
    environment:
      - SERVER_SLEEP= 0.25
      - BATCH_SIZE=32
    volumes:
      - ./modelserver/:/usr/src/app/
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker

  webserver:
    image: ankit/webserver
    build: ./webserver
    ports:
      - "5000:5000"
    networks:
      - deployml_network
    depends_on:
      - redis
    env_file:
      - app.env
    environment:
      - CLIENT_SLEEP=0.25
      - CLIENT_MAX_TRIES=100
    volumes:
      - ./webserver/:/usr/src/app/
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  deployml_network: